# Generated by Django 5.1.6 on 2025-03-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='b_price',
            new_name='buying_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='s_price',
        ),
    ]
