# Generated by Django 5.1.6 on 2025-03-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
