# Generated by Django 5.1.6 on 2025-03-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0002_remove_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='b_price',
            new_name='buying_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='s_price',
            new_name='selling_price',
        ),
    ]
