# Generated by Django 4.0.3 on 2025-03-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0008_rename_price_product_b_price_product_s_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=2),
        ),
    ]
