# Generated by Django 4.0.3 on 2025-03-02 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imsApp', '0010_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_type', models.CharField(choices=[('owed_to_me', 'Ninadai'), ('owed_by_me', 'Ninadaiwa')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Haijalipwa'), ('partially_paid', 'Limeanza kulipwa'), ('paid', 'Limekamilika')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
