# Generated by Django 4.0.3 on 2025-03-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0012_employee_alter_debt_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('salary', 'Salary Payment'), ('rent', 'Office Rent'), ('utilities', 'Utilities (Water, Electricity, Internet)'), ('supplies', 'Office Supplies'), ('transport', 'Transport & Fuel'), ('marketing', 'Marketing & Advertising'), ('others', 'Other Expenses')], default='others', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_spent', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
